# Generated by Django 5.2 on 2025-05-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_alter_thread_options_thread_created_thread_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='created',
        ),
        migrations.AlterField(
            model_name='thread',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
