# Generated by Django 5.2 on 2025-05-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_remove_thread_created_alter_thread_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-updated']},
        ),
    ]
